image: node:latest

stages:
  - build
pages:
  stage: build
  script:
      - npm install
      - npx resumed render resume.json --theme jsonresume-theme-mooser
      - mkdir public 
      - mv resume.html public/cv.html
  artifacts:
    paths:
      - public
